[package]
name = "thirtyfour_download_file"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
thirtyfour = "0.33.0"
tokio = { version = "1.39.2", features = ["full"] }
env_logger = "0.11.3"
log = "0.4.21"
chrono = "0.4.38"
rustfmt = "0.10.0"
